# Config for log-jar
base_url = "https://vachzar.github.io/log-jar"
title = "JARxAI log"
description = "Vachzar's notes & logs"
default_language = "en"
compile_sass = true
theme = "zolanight"
build_search_index = false

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]

[extra.zolanight]
theme = "tokyonight"
home_list_latest_blog_posts = true
